export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BOARD_ROUTE = '/'
export const ANNOUNCEMENT_ROUTE = '/announcement'
export const CREATEANNOUNCEMENT_ROUTE = '/create'
export const USERANNOUNCEMENT_ROUTE = '/userAnnouncement'
export const USERANNOUNCEMENTPAGE_ROUTE = '/userAnnouncementPage'
export const EDITANNOUNCEMENT_ROUTE = '/edit'
export const ADMINPAGE_ROUTE = '/admin'
export const USERALLANNOUNCEMENT_ROUTE = '/userAllAnnouncement'
export const MODERATIONANNOUNCEMENTPAGE_ROUTE = '/moderation'
export const FAVOURITEANNOUNCEMENTPAGE_ROUTE = '/favourite'

